#!/bin/bash

set -ex

mkdir -p ~/tmp/Alien-Build
cd ~/tmp/Alien-Build
curl -L https://github.com/Perl5-Alien/Alien-Build/tarball/master | tar zxf -
cd $(ls -1)
dzil-dzil authordeps --missing | dzil-cpanm -n
dzil-dzil install --install-command 'dzil-cpanm -n .'


