#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

git clone --depth 2 https://github.com/plicease/Alien-Build.git /tmp/Alien-Build
cd /tmp/Alien-Build

dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n

dzil install

git clone --depth 2 https://github.com/plicease/Alien-Build-MB.git /tmp/Alien-Build-MB
cd /tmp/Alien-Build-MB

dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n

dzil install

cpanm Dist::Zilla

git clone --depth 2 https://github.com/plicease/Dist-Zilla-Plugin-AlienBuild.git /tmp/Dist-Zilla-Plugin-AlienBuild
cd /tmp/Dist-Zilla-Plugin-AlienBuild

dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n

dzil install
